### ISSUE TITLE
fieldName usage

### ISSUE THREAD

**Issue by lmangani** [robey/crow-metrics#1]
Hi @robey - first of all thanks for your work on crow and for sharing it!

I'm trying to leverage crow for a use case where i need to define the `fieldName` alongside metrics dynamically. Looking at the code this seems to be currently impossible outside of the influxDB connector options - before working on a patch, I wanted to check with you if this is actually the case and or if you have an approach.

##### Current (actual):
```
metrics.increment(metrics.counter("method", { "some": "tag" }) );

# generated by crow 4.0.1
method,some=tag value=10 1522311210000000000
```

##### Ideal (fictional):
```
metrics.increment(metrics.counter("method", { "some": "tag" }, "myfieldName") );

# generated by crow 4.0.1
method,some=tag myfieldName=10 1522311210000000000
```

Thanks in advance!

**Comment by robey** [comment]
Haha, I actually thought about this when I realized that influx has a 3rd name field, but I wasn't sure what to do about it! Your idea sounds good: an optional 3rd parameter that defaults to "value" and is only used by the influx exporter.

(I kinda pulled "value" out of nowhere... is there a consensus within influx on what the default should be there?)

**Comment by lmangani** [comment]
@robey thanks for the reply! This is quite common in both Influx and Prometheus where a same "metric" can contain several values internally - also used to add aggregations, etc. Is this something you have an easy way of adding or shall I try patch?

**Comment by robey** [comment]
Yeah, I think I can do it pretty easily! I wonder if this would have been a better way to export distributions...

**Comment by lmangani** [comment]
Awesome! BTW That's how I believe Telegraf does it also when "aggregating" metrics, basically adding prefixed custom series to the same counter, ie: `avg_`, `max_`, `min_` etc. Looking forward to this change and happy to help out if useful.

**Comment by robey** [comment]
does this look like what you're going for?

**Comment by lmangani** [comment]
Just wanted to say thanks once more @robey I'll be an avid user and contributor ;)
